### ISSUE TITLE
Externally added recipes don't show ingredients in JEI

### ISSUE THREAD

**Issue by Cynosphere** [elytra/Thermionics#10]
![](https://totallynotavir.us/i/s1g6hbgs.png)

Code used:
```java
ItemIngredient ribbon = ItemIngredient.of(new ItemStack(ThermionicsItems.INGREDIENT, 1, EnumIngredient.RIBBON.ordinal()));
ItemIngredient anyFabric = new WildcardNBTIngredient(ThermionicsItems.FABRIC_SQUARE);

SergerRecipe varScarf = new SergerRecipe(
    new ShapedInventoryRecipe(
        new ItemStack(ModItems.scarf),
        3, 3,
        3, 2,
        false,
        anyFabric, null, anyFabric,
        ribbon, ribbon, ribbon
    ),
    6,
    10
);
MachineRecipes.register(varScarf);
```

**Comment by falkreon** [comment]
Interesting. Normally these should be picked up, but it depends on when you registered the recipe versus when JEI invokes its plugin callbacks. I don't control JEI's timing on this, and chances are if you're using Init or PostInit, you're too late.

I strongly reccommend using a `@SubscribeEvent `on `RegistryEvent.Register<IRecipe>`. That's where the builtin recipes are registered, and it's guaranteed to happen after `RegistryEvent.Register<Item>` and `RegistryEvent.Register<Block>` where you set up everything you need for it.

**Comment by falkreon** [comment]
One problem that's definitely my concern is that the background drawable in that image is vertically squished. What GUI scale is that on, and does that change if you change scales?

**Comment by Cynosphere** [comment]
My recipes are already using SubscriberEvent and the event is registered to the bus at pre init if it can find the mod.

As far as GUI scale, Normal was used in that screenshot. Changing the scale does not fix the scaling of the image at all.

**Comment by falkreon** [comment]
Well I just figured out the problem, looking at it several months later: At `preInit`, both `ThermionicsItems.INGREDIENT` and `ThermionicsItems.FABRIC_SQUARE` are null. If you haven't already, please move your code to `RegistryEvent.Register<IRecipe>` as originally requested.
