### ISSUE TITLE
Unexpected hard dependency on ProbeDataAPI

### ISSUE THREAD

**Issue by SDUBZ** [elytra/Thermionics#5]
Forge:1.11.2-2304
minecraft: 1.11.2
thermionics: Thermionics-MC1.11.2_ver1.0.8b
common capabilities: CommonCapabilities-1.11.2-1.3.3

first crash i thought it was from not having probe api so i added that
crash report:
1: 
[crash-2017-05-23_04.42.26-client.txt](https://github.com/elytra/Thermionics/files/1019927/crash-2017-05-23_04.42.26-client.txt)

2: 
[crash-2017-05-21_10.49.05-client.txt](https://github.com/elytra/Thermionics/files/1019929/crash-2017-05-21_10.49.05-client.txt)

**Comment by exaskye** [comment]
The first is indeed from missing ProbeDataAPI. The second looks like a BuildCraft crash, not a Thermionics one.

**Comment by SDUBZ** [comment]
but i have buildcraft disabled because of their facade issue see @unascribed http://puu.sh/vYi1R/88ae34c54a.png

**Comment by darkevilmac** [comment]
Make sure buildcraft is completely removed from your mods folder if you're not using it.

**Comment by SDUBZ** [comment]
oh i will test @darkevilmac :)

**Comment by falkreon** [comment]
Good luck with the buildcraft issue. Till then, it's puzzling to me that probedata crashed it *in this way*. I've edited the issue to reflect my primary concern here - not having probedataAPI (if you don't have fruitphone or another provider) shouldn't be a problem. Will fix.

**Comment by SDUBZ** [comment]
still getting crash without buildcraft in mods folder

crash:
[crash-2017-05-21_10.49.05-client.txt](https://github.com/elytra/Thermionics/files/1019999/crash-2017-05-21_10.49.05-client.txt)

**Comment by falkreon** [comment]
buildcrafttransport{7.99.3} [BC Transport] (buildcraft-7.99.3.jar) <-- this is still in your mods folder

That might not be the right crashlog, because it's the same one you posted earlier.

**Comment by SDUBZ** [comment]
oh sorry @falkreon heres the newer one

crash: 
[crash-2017-05-23_05.31.45-client.txt](https://github.com/elytra/Thermionics/files/1020030/crash-2017-05-23_05.31.45-client.txt)

**Comment by falkreon** [comment]
Hm. So that's HammerMill, just after it grabs the NonNullList of ores from the OreDictionary, and after it checks if it's empty. Maybe the version you've got is pre-check? Let me make a test build for ya.

**Comment by SDUBZ** [comment]
okay thanks @falkreon :)

**Comment by falkreon** [comment]
Try this: http://endless.blue/files/Thermionics-MC1.11.2_ver1.0.8.jar

I'm halfway into implementing JEI support, which might cause *different* problems, but everything *should* be functional.

**Comment by SDUBZ** [comment]
yay it got to main menu \o/ @falkreon

**Comment by SDUBZ** [comment]
wait how do you get any of the decorative blocks?
