### ISSUE TITLE
Game crashes when firebox is placed in world, NullPointer

### ISSUE THREAD

**Issue by Lothrazar** [elytra/Thermionics#6]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  AppleCore (AppleCore-mc1.12.2-3.1.0.jar)
  LoadingPlugin (Skillable-beta-10.jar)
  LoadingPlugin (Quark-r1.4-120.jar)
  IMLoadingPlugin (infinimend-1.12-1.0.2.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.7.2.jar)
  SoundFixPatchingLoader (AmbientSounds v2.2.1 mc1.12.2.jar)
  BIFLoader (BowInfinityFix-1.11.x-1.12.x-rv5.jar)
Contact their authors BEFORE contacting forge

// But it works on my machine.

Time: 12/25/17 12:53 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at com.elytradev.thermionics.data.ProbeDataSupport.registerMachineInspector(ProbeDataSupport.java:79)
	at com.elytradev.thermionics.tileentity.TileEntityMachine.<init>(TileEntityMachine.java:44)
	at com.elytradev.thermionics.tileentity.TileEntityFirebox.<init>(TileEntityFirebox.java:55)
	at com.elytradev.thermionics.block.BlockFirebox.func_149915_a(BlockFirebox.java:50)
	at net.minecraft.block.Block.createTileEntity(Block.java:1274)
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:623)
	at net.minecraft.world.World.func_180501_a(World.java:342)
	at net.minecraft.client.multiplayer.WorldClient.func_180501_a(WorldClient.java:655)
	at net.minecraft.item.ItemBlock.placeBlockAt(ItemBlock.java:180)
	at net.minecraft.item.ItemBlock.func_180614_a(ItemBlock.java:54)
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:187)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:467)
	at PlayerControllerOF.func_187099_a(PlayerControllerOF.java:96)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1577)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2252)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2018)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1806)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.elytradev.thermionics.data.ProbeDataSupport.registerMachineInspector(ProbeDataSupport.java:79)
	at com.elytradev.thermionics.tileentity.TileEntityMachine.<init>(TileEntityMachine.java:44)
	at com.elytradev.thermionics.tileentity.TileEntityFirebox.<init>(TileEntityFirebox.java:55)
	at com.elytradev.thermionics.block.BlockFirebox.func_149915_a(BlockFirebox.java:50)
	at net.minecraft.block.Block.createTileEntity(Block.java:1274)
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:623)
	at net.minecraft.world.World.func_180501_a(World.java:342)
	at net.minecraft.client.multiplayer.WorldClient.func_180501_a(WorldClient.java:655)
	at net.minecraft.item.ItemBlock.placeBlockAt(ItemBlock.java:180)
	at net.minecraft.item.ItemBlock.func_180614_a(ItemBlock.java:54)
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:187)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:467)
	at PlayerControllerOF.func_187099_a(PlayerControllerOF.java:96)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1577)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2252)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2018)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Lothrazar'/98, l='MpServer', x=646.80, y=4.00, z=689.82]]
	Chunk stats: MultiplayerChunkCache: 1088, 1088
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (450,4,452), Chunk: (at 2,0,4 in 28,28; contains blocks 448,0,448 to 463,255,463), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 237099 game time, 241808 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 24 total; [EntityVillager['Villager'/79, l='MpServer', x=582.54, y=5.00, z=639.18], EntityVillager['Villager'/80, l='MpServer', x=578.50, y=5.50, z=639.07], EntityVillager['Villager'/81, l='MpServer', x=578.86, y=5.00, z=639.92], EntityVillager['Villager'/82, l='MpServer', x=577.60, y=5.00, z=640.56], EntityVillager['Villager'/83, l='MpServer', x=578.21, y=5.00, z=640.64], EntityVillager['Villager'/84, l='MpServer', x=582.50, y=5.00, z=633.64], EntityVillager['Villager'/85, l='MpServer', x=591.47, y=5.00, z=650.38], EntityVillager['Villager'/86, l='MpServer', x=592.83, y=5.00, z=619.57], EntityVillager['Villager'/87, l='MpServer', x=597.70, y=3.94, z=634.73], EntityVillager['Villager'/88, l='MpServer', x=597.70, y=3.94, z=633.14], EntityVillager['Villager'/89, l='MpServer', x=597.70, y=3.94, z=633.93], EntityVillager['Villager'/90, l='MpServer', x=597.70, y=3.94, z=635.53], EntityVillager['Villager'/91, l='MpServer', x=593.04, y=5.00, z=650.30], EntityLatchedRenderer['unknown'/155, l='MpServer', x=646.80, y=4.00, z=689.82], EntityVillager['Villager'/92, l='MpServer', x=592.38, y=5.00, z=651.25], EntityVillager['Villager'/93, l='MpServer', x=607.00, y=5.00, z=658.94], EntityVillager['Villager'/94, l='MpServer', x=607.70, y=5.00, z=659.70], EntityVillager['Villager'/95, l='MpServer', x=607.70, y=5.00, z=658.33], EntityVillager['Villager'/96, l='MpServer', x=606.91, y=5.00, z=659.70], EntityVillager['Villager'/97, l='MpServer', x=592.11, y=5.00, z=662.20], EntityVillager['Villager'/99, l='MpServer', x=591.03, y=5.00, z=661.30], EntityVillager['Villager'/100, l='MpServer', x=591.90, y=5.00, z=661.54], EntityCreeper['Creeper'/101, l='MpServer', x=651.54, y=5.00, z=661.85], EntityPlayerSP['Lothrazar'/98, l='MpServer', x=646.80, y=4.00, z=689.82]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2748)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:426)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 202093808 bytes (192 MB) / 789557248 bytes (752 MB) up to 4277534720 bytes (4079 MB)
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:ParallelGCThreads=2 -XX:+AggressiveOpts
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.1.2568 Optifine OptiFine_1.12.2_HD_U_C7 75 mods loaded, 75 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                    | Version         | Source                                          | Signature                                |
	|:--------- |:--------------------- |:--------------- |:----------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft             | 1.12.2          | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | mcp                   | 9.42            | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | FML                   | 8.0.99.99       | forge-1.12.2-14.23.1.2568.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                 | 14.23.1.2568    | forge-1.12.2-14.23.1.2568.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | infinimend            | 1.0.2           | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | bowinfinityfix        | rv5             | minecraft.jar                                   | e250ba31147feb059b86cfd74ee61a8aeb88fb9b |
	| UCHIJAAAA | aiimprovements        | 0.0.1.3         | AIImprovements-1.12-0.0.1b3.jar                 | None                                     |
	| UCHIJAAAA | ambientsounds         | 2.0.0           | AmbientSounds v2.2.1 mc1.12.2.jar               | None                                     |
	| UCHIJAAAA | tammodized            | 0.15.3          | TamModized-1.12.1-0.15.3.jar                    | None                                     |
	| UCHIJAAAA | aov                   | 0.8.3           | AoV-1.12-0.8.3.jar                              | None                                     |
	| UCHIJAAAA | applecore             | 3.1.0           | AppleCore-mc1.12.2-3.1.0.jar                    | None                                     |
	| UCHIJAAAA | jei                   | 4.8.5.138       | jei_1.12.2-4.8.5.138.jar                        | None                                     |
	| UCHIJAAAA | appleskin             | 1.0.9           | AppleSkin-mc1.12-1.0.9.jar                      | None                                     |
	| UCHIJAAAA | architect             | 1.2.0.6         | Architect-MC1.12-1.2.0.6.jar                    | None                                     |
	| UCHIJAAAA | attributefix          | 1.0.1           | AttributeFix-1.12.2-1.0.1.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | quark                 | r1.4-120        | Quark-r1.4-120.jar                              | None                                     |
	| UCHIJAAAA | skillable             | beta-10         | Skillable-beta-10.jar                           | None                                     |
	| UCHIJAAAA | autoreglib            | 1.3-15          | AutoRegLib-1.3-15.jar                           | None                                     |
	| UCHIJAAAA | baubles               | 1.5.1           | Baubles-1.12-1.5.1.jar                          | None                                     |
	| UCHIJAAAA | bedbugs               | @VERSION@       | BedBugs-1.12-1.0.1.jar                          | None                                     |
	| UCHIJAAAA | betterbuilderswands   | 0.11.1          | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar | None                                     |
	| UCHIJAAAA | betterfoliage         | 2.1.10          | BetterFoliage-MC1.12-2.1.10.jar                 | None                                     |
	| UCHIJAAAA | bettertitlescreen     | 1.4b            | BetterTitleScreen-1.12.2-1.4b.jar               | None                                     |
	| UCHIJAAAA | bookshelf             | 2.3.515         | Bookshelf-1.12.2-2.3.515.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | ceanimals             | 1.4.0           | ceanimals-1.12-1.4.0.jar                        | None                                     |
	| UCHIJAAAA | clarity               | 1.1             | clarity-1.1.jar                                 | None                                     |
	| UCHIJAAAA | clienttweaks          | 3.1.2           | ClientTweaks_1.12-3.1.2.jar                     | None                                     |
	| UCHIJAAAA | controlling           | 3.0.5           | Controlling-3.0.5.jar                           | None                                     |
	| UCHIJAAAA | craftingtweaks        | 8.1.6           | CraftingTweaks_1.12.1-8.1.6.jar                 | None                                     |
	| UCHIJAAAA | cravings              | 1.0.5           | Cravings-1.12.2-1.0.5.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | forgecreeperheal      | 1.3.0           | creeperheal-1.12-1.3.1.jar                      | None                                     |
	| UCHIJAAAA | cyclicmagic           | 1.10.8          | Cyclic-1.12.2-1.10.8.jar                        | None                                     |
	| UCHIJAAAA | darkutils             | 1.8.190         | DarkUtils-1.12.2-1.8.190.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | diethopper            | 1.1             | diethopper-1.1.jar                              | None                                     |
	| UCHIJAAAA | dsurround             | 3.4.7.2         | DynamicSurroundings-1.12.2-3.4.7.2.jar          | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| UCHIJAAAA | presets               | 3.4.7.2         | DynamicSurroundings-1.12.2-3.4.7.2.jar          | None                                     |
	| UCHIJAAAA | emberroot             | 1.3.3           | EmberRootZoo-1.12-1.3.3.jar                     | None                                     |
	| UCHIJAAAA | enchdesc              | 1.0.4           | EnchantmentDescriptions-1.12-1.0.4.jar          | None                                     |
	| UCHIJAAAA | fencejumper           | 1.0.1           | fencejumper-1.12-1.0.1.jar                      | None                                     |
	| UCHIJAAAA | foamfix               | 0.8.2-1.12.2    | foamfix-0.8.2-1.12.2-law.jar                    | None                                     |
	| UCHIJAAAA | friendlyfire          | 1.5.8           | FriendlyFire-1.12.2-1.5.8.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | fw                    | 1.6.0           | FullscreenWindowed-1.12-1.6.0.jar               | None                                     |
	| UCHIJAAAA | ichunutil             | 7.1.4           | iChunUtil-1.12.2-7.1.4.jar                      | None                                     |
	| UCHIJAAAA | gravitygun            | 7.0.0           | GravityGun-1.12.2-7.0.1.jar                     | None                                     |
	| UCHIJAAAA | guideapi              | 1.12-2.1.4-57   | Guide-API-1.12-2.1.4-57.jar                     | None                                     |
	| UCHIJAAAA | inventorysorter       | 1.12.4+52       | inventorysorter-1.12.2-1.12.4+52.jar            | None                                     |
	| UCHIJAAAA | ironbackpacks         | 1.12.2-3.0.2-3  | IronBackpacks-1.12.2-3.0.2-3.jar                | None                                     |
	| UCHIJAAAA | jepb                  | 1.2.1           | jepb-1.12-1.2.1.jar                             | None                                     |
	| UCHIJAAAA | journeymap            | 1.12.2-5.5.2    | journeymap-1.12.2-5.5.2.jar                     | None                                     |
	| UCHIJAAAA | jeresources           | 0.8.6.28        | JustEnoughResources-1.12.2-0.8.6.28.jar         | None                                     |
	| UCHIJAAAA | kleeslabs             | 5.3.2           | KleeSlabs_1.12-5.3.2.jar                        | None                                     |
	| UCHIJAAAA | lunatriuscore         | 1.2.0.42        | LunatriusCore-1.12.2-1.2.0.42-universal.jar     | None                                     |
	| UCHIJAAAA | laserlevel            | 2.1.0.19        | LaserLevel-1.12.2-2.1.0.19-universal.jar        | None                                     |
	| UCHIJAAAA | llor                  | 1.1.4-mc1.12    | LLOverlayReloaded-1.1.4-mc1.12.jar              | None                                     |
	| UCHIJAAAA | mendingfix            | 1.0.1           | mendingfix-1.0.1.jar                            | None                                     |
	| UCHIJAAAA | mobends               | 0.24            | mobends-0.24_for_MC-1.12.jar                    | None                                     |
	| UCHIJAAAA | mousetweaks           | 2.8             | MouseTweaks-2.8-mc1.12.1.jar                    | None                                     |
	| UCHIJAAAA | naturescompass        | 1.5.1           | NaturesCompass-1.12.2-1.5.1.jar                 | None                                     |
	| UCHIJAAAA | samsocean             | 1.0.1           | OceanFloor-1.12-1.0.1.jar                       | None                                     |
	| UCHIJAAAA | placebo               | 1.1.3           | Placebo-1.12.2-1.1.3.jar                        | None                                     |
	| UCHIJAAAA | portalgun             | 7.0.0           | PortalGun-1.12.2-7.0.1.jar                      | None                                     |
	| UCHIJAAAA | quickleafdecay        | 1.2.4           | QuickLeafDecay-MC1.12.1-1.2.4.jar               | None                                     |
	| UCHIJAAAA | scannable             | 1.6.2.13        | Scannable-MC1.12-1.6.2.13.jar                   | None                                     |
	| UCHIJAAAA | schematica            | 1.8.0.167       | Schematica-1.12.2-1.8.0.167-universal.jar       | None                                     |
	| UCHIJAAAA | similsaxtranstructors | 1.12-1.0.21     | SimilsaxTranstructors-1.12-1.0.22.jar           | None                                     |
	| UCHIJAAAA | storagenetwork        | 1.12.1-1.1.1    | SimpleStorageNetwork-1.12.1-1.1.1.jar           | None                                     |
	| UCHIJAAAA | soundfilters          | 0.10_for_1.12   | SoundFilters-0.10_for_1.12.jar                  | None                                     |
	| UCHIJAAAA | stg                   | 1.12.2-1.2.3    | stg-1.12.2-1.2.3.jar                            | None                                     |
	| UCHIJAAAA | thermionics           | MC1.12_ver1.1.1 | Thermionics-MC1.12_ver1.1.1.jar                 | None                                     |
	| UCHIJAAAA | toastcontrol          | 1.3.0           | Toast Control-1.12.2-1.3.0.jar                  | None                                     |
	| UCHIJAAAA | underphangables       | 1.0.0           | underphangables-1.12.0-1.0.0.jar                | None                                     |
	| UCHIJAAAA | veinminer             | 0.38.1          | VeinMiner-1.12-0.38.1.639+134fb1e.jar           | None                                     |
	| UCHIJAAAA | veinminermodsupport   | 0.38.1          | VeinMiner-1.12-0.38.1.639+134fb1e.jar           | None                                     |
	| UCHIJAAAA | waystones             | 4.0.17          | Waystones_1.12.1-4.0.17.jar                     | None                                     |
	| UCHIJAAAA | weirdinggadget        | 1.0             | weirdinggadget-1.12.1-2.0.4-universal.jar       | None                                     |

	Loaded coremods (and transformers): 
AppleCore (AppleCore-mc1.12.2-3.1.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
LoadingPlugin (Skillable-beta-10.jar)
  vazkii.skillable.base.asm.ClassTransformer
LoadingPlugin (Quark-r1.4-120.jar)
  vazkii.quark.base.asm.ClassTransformer
IMLoadingPlugin (infinimend-1.12-1.0.2.jar)
  net.crazysnailboy.mods.infinimend.asm.IMClassTransformer
BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.7.2.jar)
  org.blockartistry.DynSurround.asm.Transformer
SoundFixPatchingLoader (AmbientSounds v2.2.1 mc1.12.2.jar)
  com.creativemd.ambientsounds.soundfix.SoundFixTransformer
BIFLoader (BowInfinityFix-1.11.x-1.12.x-rv5.jar)
  com.github.parker8283.bif.Transformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 385.46' Renderer: 'GeForce GT 730/PCIe/SSE2'
	Launched Version: forge-14.23.1.2568
	LWJGL: 2.9.4
	OpenGL: GeForce GT 730/PCIe/SSE2 GL version 4.5.0 NVIDIA 385.46, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [16x16]Dirty Bricks V1.1.1 For MC 1.11.zip, Rainy Day (1_11).zip, VanillaTweaks_3D.zip, VanillaTweaks_BedrockAlt.zip, VanillaTweaks_ChantGlint.zip, VanillaTweaks_DiminishingTools.zip, VanillaTweaks_Diversity.zip, VanillaTweaks_NoDirtPebble.zip, VanillaTweaks_QUIETER.zip, VanillaTweaks_RainbowExp.zip, VanillaTweaks_RedstoneUtility.zip, VanillaTweaks_TextFixes.zip, VanillaTweaks_UniformOres.zip, ContrastSymmetry1.11.2-1.0.zip, [1.10.2]Dramatic Skys [v1.7].zip (incompatible)
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_C7
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 385.46
	OpenGlRenderer: GeForce GT 730/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by falkreon** [comment]
Appears to be a regression of #5 . Will look into this; in the meantime, installing the ProbeDataProvider API is a workaround.

**Comment by Lothrazar** [comment]
Nothing on Readme or anything else lists this API as a dependency.   In fact it seems to not even exist? What is this? is it a mod?  https://minecraft.curseforge.com/search?search=ProbeDataProvider

**Comment by exaskye** [comment]
Because obviously if it's not on Curse, it doesn't exist. (Never mind the fact Thermionics isn't on Curse either.)

https://github.com/elytra/ProbeDataProvider
