### ISSUE TITLE
[Suggestion] Use hammers to craft metal plates

### ISSUE THREAD

**Issue by LemmaEOF** [elytra/Thermionics#8]
Thermionics doesn't have any way to make metal plates. While that isn't yet a problem since it doesn't use any metal plates, it might become an issue later on. How about Thermionics hammers being usable to craft metal plates, maybe hammer + 8 ingot = 8 plates, 8/16/32 durability off hammer or something similar?

~~this totally isn't because I need a way to make boiler blocks on openpack or anything~~

**Comment by falkreon** [comment]
Unfortunately, I can't help you with that. Thermionics will never use plates. However, it will soon start taking initiative on some alloys and gears as I refocus it on making it fully self-sufficient.
